---
title: "Conferences and teaching"
---

## Conferences (selection)

* 2020 - Talk at [ELLIS Health Workshop: Explainable Machine Learning & Biological Mechanisms](https://ellis.eu/events/ellis-health-workshop-explainable-machine-learning-biological-mechanisms), virtual
* 2020 - Invited keynote at [EuroBioc 2020](https://eurobioc2020.bioconductor.org), virtual
* 2020 - Invited talk at [e-RUM 2020](https://2020.erum.io), virtual
* 2019 - Invited keynote at [Single Cell OMICS data analysis workshop](https://canceropole-paca.com/agenda/single-cell-omics-data-analysis-workshop-2nd-edition/), Nice
* 2018 - Invited tutorial at [New Directions in Single Cell Analysis](http://www.sound-biomed.eu/2018/02/28/final-consortium-meeting/), Heidelberg
* 2017 - Talk at [Stanford - EMBL Conference on Personalized Health](https://events.stanford.edu/events/706/70645/), Stanford 
* 2017 - Talk at [Joint Statistical Meetings](https://ww2.amstat.org/meetings/jsm/2017/), Baltimore
* 2017 - Invited talk at [Heidelberger Kolloquium Medizinische Biometrie](https://www.klinikum.uni-heidelberg.de/medizinische-informatik/willkommen/veranstaltungen-und-termine/kolloquium/kolloquium/kolloquium), Heidelberg
* 2017 - Flash-talk at [EMBO|EMBL Symposium: From Single- to Multiomics: Applications and Challenges in Data Integration](https://www.embo-embl-symposia.org/symposia/2017/EES17-10/), Heidelberg
* 2017 - Talk at [Statistical Computing Workshop](https://sysbio.uni-ulm.de/ocs/index.php/statcomp/statcomp17), Reisenburg 
* 2014 - Talk at [International Symposium on Nonlinear Theory and its Applications](https://chaos.keiei.shikoku-u.ac.jp/NOLTA14/), Lucerne (*best paper award*)




## Conference (Co-)Organisation:

* 2021 - EMBO Practical course: Integrative Analysis of Multi-Omics (*postponed to 2022*)
* 2016 - 18th EMBL Phd Symposium: Life By Numbers: Towards Quantitative Biology
17 - 19 Nov 2016, EMBL Heidelberg

## Teaching

* 2020 - *Computational single-cell course* at University Heidelberg
* 2020 - *Data Analysis for Life Sciences* at University Heidelberg
* 2016 - Teaching assistant for *Statistical methods in high throughput data analysis* at EMBL
* 2011-2013  - Teaching assistant for *Linear Algebra* and *Complex Analysis* at University Heidelberg


## Supervision:

* ongoing - Donald Hansen, Master rotation project (Molecular Biotechnology, Heidelberg University) - co-supervision with Rajbir Batra
* ongoing - Florin Walter, Master thesis (Physics, Heidelberg University)
* 2020 - Jana Braunger, Bachelor thesis (Molecular Biotechnology, Heidelberg University)
* 2020 - Michael Altenmüller, Master thesis (Mathematics, Heidelberg University) - main supervisors: Ulrich Koethe and Jens Müller